apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: playground
  namespace: dev
spec:
  destination:
    namespace: dev
    server: 'https://kubernetes.default.svc'
  project: default
  source:
    repoURL: https://github.com/suhyeonahn/argo-playground
    targetRevision: HEAD
    path: .
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
